### ISSUE TITLE
Actual vs. theoretical framerates

### ISSUE THREAD

**Issue by XavKearney** [HPCE/hpce-2018-cw6#9]
In the README, it's quoted a few times that both the reference camera and the spiking camera are operating at 3000 FPS, with the traditional camera operating at 30 FPS.

However, the background video file we've been given is converted to MJPEG within `video_to_mjpeg.sh` assuming a framerate of 30s, and that `.mjpeg` file is then used for all the cameras. Does this not mean that the whole application is really running the reference & spiking cameras at 30 FPS, and the traditional camera at 0.3 FPS (with the default oversampling of 100)? You can confirm this by looking at the event files directly and seeing that the `t` column which indicates the frame number only goes up to 486 (for the 19 second video).

Have I misunderstood something? Or is this a deliberately downsized version of the real application?

**Comment by jjd06** [comment]
That's correct. The input video is the "3000 FPS" (upsampled from "2500 FPS") source. After running

`scripts/standard_flow.sh media/big_buck_bunny_scene_small.mp4 random all 100 0`,

you should find that `media/big_buck_bunny_scene_small.true.events`, `media/big_buck_bunny_scene_small.true.events` and `media/big_buck_bunny_scene_small.spiking.events` all have frame numbers 0--486 (because these operate at "3000 FPS", while `media/big_buck_bunny_scene_small/w/objects-trad-detected-tmp.events` only has frame numbers 0--3 ("30 FPS"). The latter's events are then replicated (100 times each, in this case) to form `media/big_buck_bunny_scene_small.trad.events`.

**Comment by XavKearney** [comment]
Okay, great. Thank you.
